site_name: OSG Virtual School 2021
site_url: https://opensciencegrid.org/virtual-school-2021/
repo_name: null
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - pymdownx.details
  - toc:
      permalink: True

extra_css:
  - stylesheets/code-highlight.css

nav:
  - Home:                           index.md
  - Schedule:                       schedule.md
  - Public Lectures:                public-lectures.md
  - Materials:
      - Overview:                   materials/index.md
      - HTC Exercises:
        - Exercise 1.1:             materials/htcondor/part1-ex1-login.md
        - Exercise 1.2:             materials/htcondor/part1-ex2-commands.md
        - Exercise 1.3:             materials/htcondor/part1-ex3-jobs.md
        - Exercise 1.4:             materials/htcondor/part1-ex4-logs.md
        - Exercise 1.5:             materials/htcondor/part1-ex5-request.md
        - Exercise 1.6:             materials/htcondor/part1-ex6-remove.md
        - Bonus Exercise 1.7:       materials/htcondor/part1-ex7-compile.md
        - Exercise 2.1:             materials/htcondor/part2-ex1-files.md
        - Exercise 2.2:             materials/htcondor/part2-ex2-queue-n.md
        - Exercise 2.3:             materials/htcondor/part2-ex3-queue-from.md
        - Bonus Exercise 2.4:       materials/htcondor/part2-ex4-queue-matching.md
        - Bonus Exercise 3.1:       materials/htcondor/part3-ex1-queue.md
        - Bonus Exercise 3.2:       materials/htcondor/part3-ex2-status.md
        - Bonus Exercise 3.3:       materials/htcondor/part3-ex3-job-retry.md
      - OSG Exercises:
        - Exercise 1.1:             materials/osg/part1-ex1-submit-refresher.md
        - Exercise 1.2:             materials/osg/part1-ex2-login-scp.md
        - Exercise 1.3:             materials/osg/part1-ex3-submit-osg.md
        - Exercise 1.4:             materials/osg/part1-ex4-hardware-diffs.md
        - Exercise 1.5:             materials/osg/part1-ex5-software-diffs.md
        - Exercise 2.1:             materials/osg/part2-ex1-troubleshooting.md
      - Software Exercises:
        - Exercise 1.1:             materials/software/part1-ex1-download.md
        - Exercise 1.2:             materials/software/part1-ex2-wrapper.md
        - Exercise 1.3:             materials/software/part1-ex3-arguments.md
        - Exercise 2.1:             materials/software/part2-ex1-compiling.md
        - Exercise 2.2:             materials/software/part2-ex2-prepackaged.md
        - Exercise 2.3:             materials/software/part2-ex3-python.md
        - Exercise 2.4:             materials/software/part2-ex4-matlab.md
        - Exercise 2.5:             materials/software/part2-ex5-conda.md
        - Exercise 3.1:             materials/software/part3-ex1-singularity.md
        - Exercise 4.1:             materials/software/part4-ex1-singularity-options.md
        - Exercise 4.2:             materials/software/part4-ex2-docker.md
        - Exercise 4.3:             materials/software/part4-ex3-docker-build.md
      - Data Exercises:
        - Exercise 1.1:             materials/data/part1-ex1-data-needs.md
        - Exercise 1.2:             materials/data/part1-ex2-file-transfer.md
        - Exercise 1.3:             materials/data/part1-ex3-blast-split.md
        - Exercise 2.1:             materials/data/part2-ex1-blast-proxy.md
        - Exercise 2.2:             materials/data/part2-ex2-stash-shared.md
        - Exercise 2.3:             materials/data/part2-ex3-stash-unique.md
        - Bonus Exercise 3.1:       materials/data/part3-ex1-input.md
        - Bonus Exercise 3.2:       materials/data/part3-ex2-output.md
      - Checkpointing Exercises:
          Exercise 1.1:             materials/checkpoint/part1-ex1-checkpointing.md
      - Workflow Exercises:
        - Exercise 1.1:             materials/workflows/part1-ex1-simple-dag.md
        - Exercise 1.2:             materials/workflows/part1-ex2-mandelbrot.md
        - Exercise 1.3:             materials/workflows/part1-ex3-complex-dag.md
        - Exercise 1.4:             materials/workflows/part1-ex4-failed-dag.md
        - Bonus Exercises 1.5:      materials/workflows/part1-ex5-challenges.md
      - Containers and GPUs :
        - Exercise 1.1:             materials/gpus/part1-ex1-containers-overview.md
        - Exercise 1.2:             materials/gpus/part1-ex2-cpu-jobs.md
        - Exercise 1.3:             materials/gpus/part1-ex3-gpu-jobs.md
  - Participant Tips:               participant-tips.md
  - Staff:                          staff.md
